# Generated by Django 5.1.5 on 2025-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
