# Generated by Django 5.1.5 on 2025-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0002_rename_username_users_name_users_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='identifiant',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
