# Generated by Django 5.1.5 on 2025-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0003_users_identifiant_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='identifiant',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
