# Generated by Django 5.1.5 on 2025-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0004_alter_users_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='badge_pass',
            field=models.CharField(auto_created=True, blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='identifiant',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
