# Generated by Django 5.2.5 on 2025-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0005_alter_users_badge_pass_alter_users_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
