# Generated by Django 5.2.5 on 2025-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_serrure', '0007_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
